version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python kisagold/manage.py migrate &&
             python kisagold/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=kisagold.settings
      - POSTGRES_DB=kisagold
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - ALLOWED_HOSTS=localhost,127.0.0.1,primary-gabi-persona-global-software-fe95a607.koyeb.app,.koyeb.app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=kisagold
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data: 